### ISSUE TITLE
[Feature] Implement Linux's hexdump command features into Hexdump

### ISSUE THREAD

**Issue by ZackeryRSmith** [KeithBrown39423/Hexdump#10]
# [Feature]

## Feature Suggestion

Hexdump doesn't currently implement all features from the linux built-in hexdump utility command. As such Hexdump isn't currently a replacement for the hexdump command. Until Hexdump has these features Hexdump can't be concidered a viable replacement for the built-in one.

## Use Case

If a end-user want's to use Hexdump as a replacement for the built-in, they would lack features that the original had. Which in their use case may just be the decision of using Hexdump or sticking with the old one.

## Your Environment

- Operating System: Arch Linux x86_64 (running linux kernel 6.1.38-1-lts)
- Project Version/Commit: v1.0.2

**Comment by KeithBrown39423** [comment]
@ZackeryRSmith Can you add a list of all the features that the original Hexdump provides?

**Comment by ZackeryRSmith** [comment]
output taken directly from `hexdump --help` for more indepth info on each feature I'd check `man hexdump`
```
Usage:
 hexdump [options] <file>...

Display file contents in hexadecimal, decimal, octal, or ascii.

Options:
 -b, --one-byte-octal      one-byte octal display
 -c, --one-byte-char       one-byte character display
 -C, --canonical           canonical hex+ASCII display
 -d, --two-bytes-decimal   two-byte decimal display
 -o, --two-bytes-octal     two-byte octal display
 -x, --two-bytes-hex       two-byte hexadecimal display
 -L, --color[=<mode>]      interpret color formatting specifiers
                             colors are enabled by default
 -e, --format <format>     format string to be used for displaying data
 -f, --format-file <file>  file that contains format strings
 -n, --length <length>     interpret only length bytes of input
 -s, --skip <offset>       skip offset bytes from the beginning
 -v, --no-squeezing        output identical lines

 -h, --help                display this help
 -V, --version             display version

Arguments:
 <length> and <offset> arguments may be followed by the suffixes for
   GiB, TiB, PiB, EiB, ZiB, and YiB (the "iB" is optional)

For more details see hexdump(1).
```

**Comment by KeithBrown39423** [comment]
--color will be handled with a config, instead of an argument
--no-squeezing will be flipped. squeezing  is disabled by default and you turn it on with --squeezing
Because I have no clue how they work, I will not be implementing the format strings. I might add them in a later version if I ever figure out how they work
the two-byte format options will be added in a minor version after there is a stable zig release
-C (--canonical) will be replaced with a --one-byte-hex option and an --ascii option
