### ISSUE TITLE
[Feature] Create a template for issues

### ISSUE THREAD

**Issue by ZackeryRSmith** [KeithBrown39423/Hexdump#11]
# [Feature]

## Feature Suggestion

Just like this feature template please add one for creating issues, as currently you can only create enhancements.

## Use Case

When trying to track an issue

**Comment by KeithBrown39423** [comment]
Thank you for this, I completely forgot to do this

**Comment by KeithBrown39423** [comment]
This was deleted when I had issues between the dev branch and the release.
