### ISSUE TITLE
[Feature] Add support for MacOS

### ISSUE THREAD

**Issue by ZackeryRSmith** [KeithBrown39423/Hexdump#30]
# [Feature]

The term "cross-platform" is quite misleading as MacOS is missing support

## Feature Suggestion

Add support for the MacOS systems

## Your Environment (if applicable)

- Operating System: MacOS Sonoma
- Project Version/Commit: 14.4.1

**Comment by KeithBrown39423** [comment]
This will be done with v2 and zig

**Comment by KeithBrown39423** [comment]
This should be fixed with the latest release. As I don't have a MacOS device, could you please test this @ZackeryRSmith?

**Comment by ZackeryRSmith** [comment]
Seems to work fine
