### ISSUE TITLE
[Feature] Release binaries

### ISSUE THREAD

**Issue by ZackeryRSmith** [KeithBrown39423/Hexdump#34]
Currently you release bundled up files. I think it would be a better idea to release the binaries as-is

**Comment by KeithBrown39423** [comment]
The reason I bundled them was because the windows binary had two files and I felt it would be weird to have one zip and two binaries.

**Comment by ZackeryRSmith** [comment]
I find it's more weird to do that. I recommend doing what most projects do and just release both the windows binaries in the releases.

Additionally this is better as if I just want one windows binary why get both...

**Comment by KeithBrown39423** [comment]
Fixed. The windows build had a .pdb file but I guess that's not very important.
